# Generated by Django 4.2.8 on 2026-07-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='patient_avatars/'),
        ),
    ]
