# Generated by Django 4.2.8 on 2026-07-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patient_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='country',
            field=models.CharField(default='Bangladesh', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Bangladeshi mobile number e.g. +88017XXXXXXXX', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='country',
            field=models.CharField(default='Bangladesh', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='district',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chattogram', 'Chattogram'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Barishal', 'Barishal'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh'), ('Other BD District', 'Other BD District')], default='Dhaka', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Bangladeshi mobile number e.g. +88017XXXXXXXX', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='registration_number',
            field=models.CharField(blank=True, help_text='BMDC Registration Number e.g. A-12345', max_length=50),
        ),
    ]
