# Generated by Django 4.2.8 on 2026-07-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_doctor_country_doctor_phone_number_patient_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bmdc_certificate',
            field=models.FileField(blank=True, help_text='BMDC certificate / license image or PDF', null=True, upload_to='doctor_certificates/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='nid_number',
            field=models.CharField(blank=True, help_text='Bangladeshi NID Number for verification', max_length=30),
        ),
        migrations.AddField(
            model_name='doctor',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'BMDC Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
