# Generated by Django 4.2.8 on 2026-07-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_doctor_bmdc_certificate_doctor_nid_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='identity_document',
            field=models.FileField(blank=True, help_text='NID card or Birth Certificate image/PDF', null=True, upload_to='patient_identity_docs/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='nid_or_birth_reg',
            field=models.CharField(blank=True, help_text='Bangladeshi NID or Birth Registration Number', max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'BD Citizen Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
