# Generated by Django 4.2.8 on 2026-08-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_patient_identity_document_patient_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_avatars/'),
        ),
    ]
