# Generated by Django 6.0.7 on 2026-08-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_appnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this API config', max_length=100)),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('groq', 'Groq Cloud'), ('openai', 'OpenAI'), ('deepseek', 'DeepSeek'), ('custom', 'Custom OpenAI-compatible')], max_length=20)),
                ('api_key', models.CharField(help_text='API key (stored encrypted in production)', max_length=200)),
                ('model_name', models.CharField(default='gemini-2.0-flash', help_text='Model identifier e.g. gemini-2.0-flash, llama-3.3-70b-versatile', max_length=100)),
                ('base_url', models.CharField(blank=True, help_text='Custom base URL for OpenAI-compatible APIs (for Groq, DeepSeek, Custom)', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower number = higher priority. Tried first.')),
                ('max_requests_per_minute', models.PositiveIntegerField(default=60, help_text='Rate limit for this provider')),
                ('current_usage_count', models.PositiveIntegerField(default=0, help_text='Usage in current minute window')),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'created_at'],
            },
        ),
    ]
