# Generated by Django 6.0.7 on 2026-08-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_ai_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprovider',
            name='provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('groq', 'Groq Cloud'), ('openai', 'OpenAI'), ('deepseek', 'DeepSeek'), ('openrouter', 'OpenRouter'), ('custom', 'Custom OpenAI-compatible')], max_length=20),
        ),
    ]
