# Generated by Django 6.0.7 on 2026-08-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_openrouter_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='avatar_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='avatar_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
