# Generated by Django 6.0.7 on 2026-08-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_subscription_plan_remove_subscription_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Consultation fee in BDT', max_digits=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Total years of medical practice experience'),
        ),
    ]
