# Generated by Django 6.0.7 on 2026-08-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_doctor_consultation_fee_doctor_experience_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='custom_dose_times',
            field=models.JSONField(blank=True, default=list, help_text="Custom dose times in HH:MM format, e.g. ['08:00', '14:00', '20:00']"),
        ),
    ]
