# Generated by Django 4.2.8 on 2026-08-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_patient_custom_dose_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Refundable wallet balance in BDT', max_digits=12),
        ),
    ]
