# Generated by Django 4.2.8 on 2026-08-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_patient_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_edit_rule', models.CharField(choices=[('enabled', '4-Hour Rule Enabled'), ('disabled', 'No Restriction — Book Anytime')], default='enabled', help_text='If enabled, patients can only edit appointments at least 4 hours before the scheduled time. If disabled, patients can edit anytime based on slot availability.', max_length=20)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
