# Generated by Django 6.0.7 on 2026-08-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bmdc_registration_year',
            field=models.PositiveIntegerField(blank=True, help_text='BMDC Registration Year', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='degrees',
            field=models.TextField(blank=True, help_text='e.g. MBBS, MD (Cardiology), FCPS'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='designation',
            field=models.CharField(blank=True, help_text='e.g. Consultant, Associate Professor, HOD', max_length=150),
        ),
    ]
