# Generated by Django 6.0.7 on 2026-08-30 22:59

from django.db import migrations


def populate_doctor_fields(apps, schema_editor):
    Doctor = apps.get_model("accounts", "Doctor")
    doctors = Doctor.objects.select_related("user").all()
    for doctor in doctors:
        specialty = doctor.specialty or "General Medicine"
        doctor.designation = f"Consultant {specialty}"
        doctor.degrees = f"MBBS, MD ({specialty})"
        if doctor.registration_number and doctor.registration_number.startswith("BMDC-"):
            num = doctor.registration_number.replace("BMDC-", "")
            try:
                year = 2010 + (int(num) % 11)
            except ValueError:
                year = 2015
            doctor.bmdc_registration_year = year
        else:
            doctor.bmdc_registration_year = 2015
        doctor.save(update_fields=["designation", "degrees", "bmdc_registration_year"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_add_patientvisit"),
    ]

    operations = [
        migrations.RunPython(populate_doctor_fields, migrations.RunPython.noop),
    ]
