# Generated by Django 4.2.8 on 2026-08-31 16:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_add_news_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='platform_commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Platform commission rate (percentage) charged on each paid appointment. Default: 3%%', max_digits=5),
        ),
    ]
