# Generated by Django 4.2.8 on 2026-09-01 06:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_sync_commission_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='platform_commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Platform commission rate (percentage) charged on each paid appointment. Default: 10%%', max_digits=5),
        ),
    ]
