# Generated by Django 4.2.8 on 2026-09-01 07:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_sitesettings_platform_commission_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='platform_commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('7.50'), help_text='Platform commission rate (percentage) charged on each paid appointment. To change: edit default here, then run makemigrations + migrate.', max_digits=5),
        ),
    ]
