# Generated by Django 4.2.8 on 2026-09-03
from datetime import date
from django.db import migrations, models


def populate_doctor_fields(apps, schema_editor):
    Doctor = apps.get_model("accounts", "Doctor")
    for doctor in Doctor.objects.all():
        if not doctor.date_of_birth:
            doctor.date_of_birth = date(1990, 1, 1)
        if not doctor.gender:
            doctor.gender = "Other"
        doctor.save(update_fields=["date_of_birth", "gender"])


def populate_patient_fields(apps, schema_editor):
    Patient = apps.get_model("accounts", "Patient")
    for patient in Patient.objects.all():
        if not patient.date_of_birth:
            patient.date_of_birth = date(2000, 1, 1)
        if not patient.gender:
            patient.gender = "Other"
        patient.save(update_fields=["date_of_birth", "gender"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_alter_sitesettings_platform_commission_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="date_of_birth",
            field=models.DateField(default=date(1990, 1, 1), help_text="Required — used to calculate age and verify identity"),
        ),
        migrations.AddField(
            model_name="doctor",
            name="gender",
            field=models.CharField(default="Other", help_text="Required — Male / Female / Other", max_length=20),
        ),
        migrations.RunPython(populate_doctor_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="doctor",
            name="date_of_birth",
            field=models.DateField(help_text="Required — used to calculate age and verify identity"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="gender",
            field=models.CharField(help_text="Required — Male / Female / Other", max_length=20),
        ),
        migrations.RunPython(populate_patient_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(help_text="Required — used to calculate age and verify identity"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(help_text="Required — Male / Female / Other", max_length=20),
        ),
    ]
