# Generated by Django 4.2.8 on 2026-09-03 10:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_make_profile_fields_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='patient_refund_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('35.00'), help_text='Patient partial refund percentage on patient-initiated cancellations.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='platform_commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Platform commission rate (percentage) charged on each paid appointment.', max_digits=5),
        ),
    ]
