# Generated by Django 6.0.7 on 2026-09-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_sitesettings_patient_refund_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_signatures/'),
        ),
    ]
