# Generated by Django 4.2.8 on 2026-09-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_doctor_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='message_bn',
            field=models.TextField(blank=True, help_text='Message in Bangla', null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_bn',
            field=models.CharField(blank=True, help_text='Title in Bangla', max_length=200, null=True),
        ),
    ]
