# Generated by Django 4.2.8 on 2026-09-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_news_message_bn_news_title_bn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='preferred_language',
            field=models.CharField(choices=[('bn', 'Bangla'), ('en', 'English')], default='en', max_length=10),
        ),
    ]
