# Generated by Django 4.2.8 on 2026-07-31 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_doctor_country_doctor_phone_number_patient_country_and_more'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminderschedule',
            options={'ordering': ['scheduled_date', 'reminder_time']},
        ),
        migrations.AddField(
            model_name='medicine',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='e.g. Square, Incepta, Beximco', max_length=150),
        ),
        migrations.AddField(
            model_name='reminderschedule',
            name='reminder_time',
            field=models.TimeField(blank=True, help_text='Specific dose time (e.g. 08:00:00)', null=True),
        ),
        migrations.AddField(
            model_name='reminderschedule',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='form',
            field=models.CharField(help_text='e.g. Tablet, Capsule, Syrup, Injection', max_length=50),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='dosage',
            field=models.CharField(help_text='e.g. 1 tablet, 5ml syrup', max_length=100),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='frequency',
            field=models.PositiveIntegerField(default=1, help_text='Times per day'),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='timing_relation_to_meal',
            field=models.CharField(choices=[('before_meal', 'Before meal / খাবার আগে'), ('after_meal', 'After meal / খাবার পরে'), ('with_meal', 'With meal / খাবারের সাথে'), ('anytime', 'Anytime / যেকোনো সময়')], default='after_meal', max_length=20),
        ),
        migrations.CreateModel(
            name='AIPrescriptionScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prescription_scans/')),
                ('status', models.CharField(choices=[('pending', 'Pending Processing'), ('completed', 'Successfully Extracted'), ('failed', 'Extraction Failed')], default='pending', max_length=20)),
                ('raw_ocr_text', models.TextField(blank=True)),
                ('extracted_json', models.JSONField(blank=True, help_text='Structured medicine list extracted by Gemini Vision AI', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_scans', to='accounts.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
