# Generated by Django 4.2.8 on 2026-08-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_alter_reminderschedule_options_medicine_manufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='advice_rules',
            field=models.TextField(blank=True, help_text='Advice & lifestyle rules'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='chief_complaints',
            field=models.TextField(blank=True, help_text='e.g. Fever x 3 days, dry cough'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.CharField(blank=True, help_text='e.g. Acute Bronchitis', max_length=255),
        ),
        migrations.AddField(
            model_name='prescription',
            name='next_followup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='tests_investigations',
            field=models.TextField(blank=True, help_text='Clinical tests e.g. CBC, Serum Creatinine'),
        ),
    ]
