# Generated by Django 6.0.7 on 2026-08-18 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_appointment_edit_count'),
        ('prescriptions', '0003_prescription_advice_rules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='booking_deadline',
            field=models.DateField(blank=True, help_text='Deadline for patient to book appointment (4 days from follow-up)', null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='is_booking_confirmed',
            field=models.BooleanField(default=False, help_text='Whether patient has booked appointment for follow-up'),
        ),
        migrations.AddField(
            model_name='followup',
            name='notification_sent',
            field=models.BooleanField(default=False, help_text='Whether booking notification was sent to patient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='activates_at',
            field=models.DateTimeField(blank=True, help_text='Time when prescription becomes active (10 min before appointment)', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(blank=True, help_text='Appointment this prescription is linked to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='doctors.appointment'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Time when prescription becomes locked (4 hours after creation)', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Whether prescription editing is disabled'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('missed', 'Missed'), ('booking_required', 'Booking Required')], default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('scheduled', 'Scheduled'), ('expired', 'Expired')], default='active', max_length=20),
        ),
    ]
