# Generated by Django 6.0.7 on 2026-08-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_followup_booking_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='booking_deadline',
            field=models.DateField(blank=True, help_text='Reference deadline (4 days from follow-up)', null=True),
        ),
    ]
