# Generated by Django 4.2.8 on 2026-07-31 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_doctor_country_doctor_phone_number_patient_country_and_more'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='ai_model_used',
            field=models.CharField(default='gemini-2.5-flash', max_length=50),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='voice_logs/'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='language',
            field=models.CharField(default='bn', max_length=10),
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.TextField(blank=True, help_text='Drug or food allergies e.g. Penicillin')),
                ('chronic_conditions', models.TextField(blank=True, help_text='Known conditions e.g. Hypertension, Type 2 Diabetes')),
                ('past_surgeries', models.TextField(blank=True)),
                ('family_medical_history', models.TextField(blank=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='accounts.patient')),
            ],
        ),
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure_sys', models.PositiveIntegerField(blank=True, help_text='Systolic BP (e.g. 120)', null=True)),
                ('blood_pressure_dia', models.PositiveIntegerField(blank=True, help_text='Diastolic BP (e.g. 80)', null=True)),
                ('blood_sugar_fasting', models.DecimalField(blank=True, decimal_places=2, help_text='mmol/L', max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pulse_rate', models.PositiveIntegerField(blank=True, help_text='BPM', null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to='accounts.patient')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
    ]
