# Generated by Django 4.2.8 on 2026-08-02 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_appnotification'),
        ('patient', '0002_chatmessage_ai_model_used_chatmessage_audio_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('report_type', models.CharField(choices=[('lab_report', 'Lab Test Report'), ('external_prescription', 'External Doctor Prescription'), ('imaging', 'X-Ray / MRI / Imaging'), ('discharge_summary', 'Discharge Summary'), ('other', 'Other Medical Record')], default='lab_report', max_length=30)),
                ('test_date', models.DateField()),
                ('doctor_or_clinic', models.CharField(blank=True, help_text='Consulted doctor or clinic name', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Result description, diagnosis, or key findings')),
                ('document', models.FileField(upload_to='patient_reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.patient')),
            ],
            options={
                'ordering': ['-test_date', '-uploaded_at'],
            },
        ),
    ]
