# Generated by Django 4.2.8 on 2026-08-02 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_appnotification'),
        ('patient', '0003_patientreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('report_type', models.CharField(choices=[('lab_test', 'Lab Test Report'), ('external_prescription', 'External Doctor Prescription'), ('imaging_xray', 'X-Ray / MRI / Ultrasound'), ('other', 'Other Medical Document')], default='lab_test', max_length=30)),
                ('date_performed', models.DateField(help_text='Date when test/consultation was conducted')),
                ('doctor_or_clinic_name', models.CharField(blank=True, help_text='Name of consulting doctor or lab/clinic', max_length=150)),
                ('result_description', models.TextField(blank=True, help_text='Test results summary or medical findings')),
                ('document_file', models.FileField(help_text='Uploaded PDF or image document', upload_to='patient_health_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reports', to='accounts.patient')),
            ],
            options={
                'ordering': ['-date_performed', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PatientReport',
        ),
    ]
