# Generated by Django 6.0.7 on 2026-08-30 23:27

from django.db import migrations
import datetime


def populate_patient_fields(apps, schema_editor):
    Patient = apps.get_model("accounts", "Patient")
    patients = Patient.objects.select_related("user").all()
    genders = ["Male", "Female", "Male", "Female", "Male", "Female", "Male", "Female"]
    for idx, patient in enumerate(patients):
        if not patient.gender:
            patient.gender = genders[idx % len(genders)]
        if not patient.date_of_birth:
            year = 1990 + (idx % 30)
            month = 1 + (idx % 12)
            day = 1 + (idx % 28)
            patient.date_of_birth = datetime.date(year, month, day)
        patient.save(update_fields=["gender", "date_of_birth"])


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0006_add_patientvisit"),
    ]

    operations = [
        migrations.RunPython(populate_patient_fields, migrations.RunPython.noop),
    ]
