# Generated by Django 6.0.7 on 2026-08-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_update_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='net_doctor_payout_bdt',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount after platform fee and refunds', max_digits=8),
        ),
        migrations.AddField(
            model_name='appointment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(blank=True, help_text='bKash / SSLCommerz / Cash', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='platform_fee_bdt',
            field=models.DecimalField(decimal_places=2, default=0, help_text='3% platform fee', max_digits=8),
        ),
        migrations.AddField(
            model_name='appointment',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='appointment',
            name='refund_status',
            field=models.CharField(choices=[('none', 'No Refund'), ('partial', 'Partial Refund'), ('full', 'Full Refund')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('cancellation_pending', 'Cancellation Pending Approval'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
