# Generated by Django 6.0.7 on 2026-08-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_appointment_net_doctor_payout_bdt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('completed', 'Completed / Visited'), ('missed', 'Missed / No-Show'), ('cancelled', 'Cancelled'), ('cancellation_pending', 'Cancellation Pending Approval'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
