# Generated by Django 6.0.7 on 2026-08-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='edit_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times patient has edited this booking'),
        ),
    ]
