# Generated by Django 4.2.8 on 2026-08-23 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_patient_balance'),
        ('doctors', '0006_appointment_edit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_notes',
            field=models.TextField(blank=True, help_text='Patient notes about payment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_proof',
            field=models.FileField(blank=True, help_text='Transaction screenshot or proof', null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to='accounts.doctor'),
        ),
    ]
