# Generated by Django 4.2.8 on 2026-09-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_appointment_payment_notes_appointment_payment_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_payment_appeal_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_appeal_admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_appeal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_appeal_status',
            field=models.CharField(choices=[('none', 'No Appeal'), ('pending', 'Pending Admin Review'), ('approved_refund', 'Approved Full Refund'), ('approved_payment', 'Verified & Confirmed'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_appeal_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='platform_fee_bdt',
            field=models.DecimalField(decimal_places=2, default=0, help_text='15% platform fee', max_digits=8),
        ),
    ]
