# Generated by Django 4.2.8 on 2026-09-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_appointment_is_payment_appeal_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='max_patients',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
