# Generated by Django 4.2.8 on 2026-09-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_doctorschedule_max_patients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_verification', 'Pending Verification'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
