"""
Django settings for carebridge project.

Generated by 'django-admin startproject' using Django 6.0.7.
"""

from pathlib import Path
import os
import sys

try:
    from dotenv import load_dotenv
except ImportError:  # pragma: no cover - dependency may be absent in some environments
    def load_dotenv(*args, **kwargs):
        return False

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# Ensure .env is read into os.environ before DATABASES is configured
env_file = BASE_DIR / '.env'
if env_file.exists():
    with open(env_file, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#') and '=' in line:
                key, val = line.split('=', 1)
                os.environ[key.strip()] = val.strip()

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SECRET_KEY = 'django-insecure-#n_63m^237fjg5n&t(e-d2v4u%$68ged54tq*4!u1r5)nof3g0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")

ALLOWED_HOSTS = ['*']



# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tailwind',
    'theme',
    'django_browser_reload',
    'carebridge',
    'accounts',
    'patient',
    'doctors',
    'prescriptions',
]

TAILWIND_APP_NAME = "theme"
NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.RoleBasedAccessMiddleware',
    'accounts.middleware.NoCacheAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_browser_reload.middleware.BrowserReloadMiddleware",
]

ROOT_URLCONF = 'carebridge.urls'

JAZZMIN_SETTINGS = {
    "site_title": "CareBridge AI Admin",
    "site_header": "CareBridge AI",
    "site_brand": "CareBridge AI",
    "welcome_sign": "Welcome to CareBridge AI Admin",
    "copyright": "CareBridge AI",
    "site_logo": None,
    "show_ui_builder": False,
    "topmenu_links": [
        {"name": "CareBridge Home", "url": "home", "permissions": ["auth.view_user"]},
        {"name": "Unverified Approval Dashboard", "url": "accounts:admin_unverified_dashboard"},
        {"name": "Log Out", "url": "/logout/", "icon": "fas fa-sign-out-alt"},
    ],
    "usermenu_links": [
        {"name": "Unverified Approval Dashboard", "url": "accounts:admin_unverified_dashboard", "icon": "fas fa-user-check"},
        {"name": "Log Out", "url": "/logout/", "icon": "fas fa-sign-out-alt"},
    ],
    "icons": {
        "auth.user": "fas fa-user",
        "accounts.doctor": "fas fa-user-doctor",
        "accounts.patient": "fas fa-user-injured",
        "prescriptions.prescription": "fas fa-file-prescription",
        "prescriptions.prescriptionitem": "fas fa-pills",
        "prescriptions.medicine": "fas fa-capsules",
        "reminders.reminderschedule": "fas fa-bell",
        "followups.followup": "fas fa-calendar-check",
    },
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "sidebar": "sidebar-dark-teal",
    "sidebar_nav_small_text": False,
    "brand_colour": "navbar-success",
    "accent": "accent-teal",
    "button_classes": {
        "primary": "btn-success",
    },
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.tz',
                'carebridge.context_processors.ui_settings',
                'accounts.context_processors.notifications_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'carebridge.wsgi.application'

# Authentication Backends & Account Settings
AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "accounts:post_login_redirect"
LOGOUT_REDIRECT_URL = "home"

# Session Security
SESSION_COOKIE_AGE = 7200  # 2 hours in seconds
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# CSRF & Security Headers
CSRF_COOKIE_SECURE = False  # Set True in production with HTTPS
SESSION_COOKIE_SECURE = False  # Set True in production with HTTPS
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_HTTPONLY = True

# Database Configuration (Supports PostgreSQL and SQLite)
DB_ENGINE = os.getenv("DB_ENGINE", "sqlite")
DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    try:
        import dj_database_url
        DATABASES = {
            'default': dj_database_url.config(
                default=DATABASE_URL,
                conn_max_age=600,
                conn_health_checks=True,
            )
        }
    except ImportError:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
elif DB_ENGINE.lower() == "postgresql":
    pg_name = os.getenv('DB_NAME', 'carebridge_db')
    pg_user = os.getenv('DB_USER', 'postgres')
    pg_pass = os.getenv('DB_PASSWORD', 'postgres')
    pg_host = os.getenv('DB_HOST', 'localhost')
    pg_port = os.getenv('DB_PORT', '5432')

    use_pg = False
    try:
        import psycopg2
        conn = psycopg2.connect(dbname=pg_name, user=pg_user, password=pg_pass, host=pg_host, port=pg_port, connect_timeout=3)
        conn.close()
        use_pg = True
    except Exception as err:
        print(f"[CareBridge DB Notice] PostgreSQL authentication/connection failed ({err}). Falling back to SQLite db.sqlite3.")

    if use_pg:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': pg_name,
                'USER': pg_user,
                'PASSWORD': pg_pass,
                'HOST': pg_host,
                'PORT': pg_port,
            }
        }
    else:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Dhaka'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Load .env variables
env_file = BASE_DIR / '.env'
if env_file.exists():
    with open(env_file, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#') and '=' in line:
                key, val = line.split('=', 1)
                os.environ[key.strip()] = val.strip()

# Email Configuration (Gmail SMTP)
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 't')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'mdimran095m@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'fsqvtfqocoopccpb')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'CareBridge AI <mdimran095m@gmail.com>')

# AI Configuration
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')
GROQ_API_KEY = os.getenv('GROQ_API_KEY', '')
OPENROUTER_SITE_URL = os.getenv('OPENROUTER_SITE_URL', 'https://carebridge.ai')
OPENROUTER_SITE_TITLE = os.getenv('OPENROUTER_SITE_TITLE', 'CareBridge AI')

